services:
  nginx:
    image: nginx:1.26
    container_name: dimar_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../portal_maritimo_colombiano:/var/www/pmc:cached
      # - ../portal_ninos_dimar:/var/www/infantil:cached
    networks:
      - dimar_network

networks:
  dimar_network:
    external: true
